# Generated by Django 4.1.4 on 2023-02-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Menu name')),
                ('name1', models.CharField(max_length=50, verbose_name='Menu name1')),
                ('name2', models.CharField(max_length=50, verbose_name='Menu name2')),
                ('name3', models.CharField(max_length=50, verbose_name='Menu name3')),
                ('name4', models.CharField(max_length=50, verbose_name='Menu name4')),
                ('name5', models.CharField(max_length=50, verbose_name='Menu name5')),
                ('name6', models.CharField(max_length=50, verbose_name='Menu name6')),
                ('name7', models.CharField(max_length=50, verbose_name='Menu name7')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menues',
            },
        ),
    ]
