# Generated by Django 4.1.4 on 2023-02-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Home name')),
                ('name1', models.CharField(max_length=50, verbose_name='Home name1')),
                ('name2', models.CharField(max_length=50, verbose_name='Home name2')),
                ('name3', models.CharField(max_length=50, verbose_name='Home name3')),
                ('name4', models.CharField(max_length=50, verbose_name='Home name4')),
                ('about', models.TextField(verbose_name='Home about')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Homes',
            },
        ),
    ]
