# Generated by Django 4.1.4 on 2023-02-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ArtistFoto name')),
                ('name1', models.CharField(max_length=50, verbose_name='ArtistFoto name1')),
                ('name2', models.CharField(max_length=50, verbose_name='ArtistFoto name2')),
                ('name3', models.CharField(max_length=50, verbose_name='ArtistFoto name3')),
                ('about', models.TextField(verbose_name='ArtistFoto about')),
                ('about1', models.TextField(verbose_name='ArtistFoto about1')),
                ('about2', models.TextField(verbose_name='ArtistFoto about2')),
                ('about3', models.TextField(verbose_name='ArtistFoto about3')),
                ('img', models.ImageField(upload_to='media', verbose_name='ArtistFoto image')),
            ],
            options={
                'verbose_name': 'ArtistFoto',
                'verbose_name_plural': 'ArtistFotos',
            },
        ),
    ]
