# Generated by Django 4.1.4 on 2023-02-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_artistfoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistFotoRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ArtistFotoRight name')),
                ('name1', models.CharField(max_length=50, verbose_name='ArtistFotoRight name1')),
                ('name2', models.CharField(max_length=50, verbose_name='ArtistFotoRight name2')),
                ('name3', models.CharField(max_length=50, verbose_name='ArtistFotoRight name3')),
                ('about', models.TextField(verbose_name='ArtistFotoRight about')),
                ('about1', models.TextField(verbose_name='ArtistFotoRight about1')),
                ('about2', models.TextField(verbose_name='ArtistFotoRight about2')),
                ('about3', models.TextField(verbose_name='ArtistFotoRight about3')),
                ('img', models.ImageField(upload_to='media', verbose_name='ArtistFotoRight image')),
            ],
            options={
                'verbose_name': 'ArtistFotoRight',
                'verbose_name_plural': 'ArtistFotoRights',
            },
        ),
    ]
