# Generated by Django 4.1.4 on 2023-02-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='about',
            field=models.TextField(null=True, verbose_name='Event about'),
        ),
        migrations.AddField(
            model_name='event',
            name='about1',
            field=models.TextField(null=True, verbose_name='Event about1'),
        ),
        migrations.AddField(
            model_name='event',
            name='about10',
            field=models.TextField(null=True, verbose_name='Event about10'),
        ),
        migrations.AddField(
            model_name='event',
            name='about11',
            field=models.TextField(null=True, verbose_name='Event about11'),
        ),
        migrations.AddField(
            model_name='event',
            name='about12',
            field=models.TextField(null=True, verbose_name='Event about12'),
        ),
        migrations.AddField(
            model_name='event',
            name='about13',
            field=models.TextField(null=True, verbose_name='Event about13'),
        ),
        migrations.AddField(
            model_name='event',
            name='about14',
            field=models.TextField(null=True, verbose_name='Event about14'),
        ),
        migrations.AddField(
            model_name='event',
            name='about15',
            field=models.TextField(null=True, verbose_name='Event about15'),
        ),
        migrations.AddField(
            model_name='event',
            name='about16',
            field=models.TextField(null=True, verbose_name='Event about16'),
        ),
        migrations.AddField(
            model_name='event',
            name='about2',
            field=models.TextField(null=True, verbose_name='Event about2'),
        ),
        migrations.AddField(
            model_name='event',
            name='about3',
            field=models.TextField(null=True, verbose_name='Event about3'),
        ),
        migrations.AddField(
            model_name='event',
            name='about4',
            field=models.TextField(null=True, verbose_name='Event about4'),
        ),
        migrations.AddField(
            model_name='event',
            name='about5',
            field=models.TextField(null=True, verbose_name='Event about5'),
        ),
        migrations.AddField(
            model_name='event',
            name='about6',
            field=models.TextField(null=True, verbose_name='Event about6'),
        ),
        migrations.AddField(
            model_name='event',
            name='about7',
            field=models.TextField(null=True, verbose_name='Event about7'),
        ),
        migrations.AddField(
            model_name='event',
            name='about8',
            field=models.TextField(null=True, verbose_name='Event about8'),
        ),
        migrations.AddField(
            model_name='event',
            name='about9',
            field=models.TextField(null=True, verbose_name='Event about9'),
        ),
        migrations.AddField(
            model_name='event',
            name='name1',
            field=models.CharField(max_length=50, null=True, verbose_name='Event name1'),
        ),
        migrations.AddField(
            model_name='event',
            name='name2',
            field=models.CharField(max_length=50, null=True, verbose_name='Event name2'),
        ),
        migrations.AddField(
            model_name='event',
            name='name3',
            field=models.CharField(max_length=50, null=True, verbose_name='Event name3'),
        ),
        migrations.AddField(
            model_name='event',
            name='name4',
            field=models.CharField(max_length=50, null=True, verbose_name='Event name4'),
        ),
        migrations.AddField(
            model_name='event',
            name='name5',
            field=models.CharField(max_length=50, null=True, verbose_name='Event name5'),
        ),
    ]
