# Generated by Django 4.1.6 on 2023-02-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='PriceList name')),
                ('name1', models.CharField(max_length=50, verbose_name='PriceList name1')),
                ('name2', models.CharField(blank=True, max_length=50, verbose_name='PriceList name2')),
                ('name3', models.CharField(blank=True, max_length=50, verbose_name='PriceList name3')),
                ('name4', models.CharField(max_length=50, verbose_name='PriceList name4')),
                ('about', models.TextField(verbose_name='PriceList about')),
                ('about1', models.TextField(verbose_name='PriceList about1')),
                ('about2', models.TextField(verbose_name='PriceList about2')),
                ('about3', models.TextField(verbose_name='PriceList about3')),
                ('about4', models.TextField(verbose_name='PriceList about4')),
                ('about5', models.TextField(blank=True, verbose_name='PriceList about5')),
            ],
            options={
                'verbose_name': 'PriceList',
                'verbose_name_plural': 'PriceLists',
            },
        ),
    ]
