# Generated by Django 4.1.6 on 2023-02-15 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_pricelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='about5',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='name2',
        ),
    ]
