# Generated by Django 4.1.6 on 2023-02-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_pricelist_about5_remove_pricelist_name2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Contact name')),
                ('name1', models.CharField(max_length=50, verbose_name='Contact name1')),
                ('name2', models.CharField(max_length=50, verbose_name='Contact name2')),
                ('name3', models.CharField(max_length=50, verbose_name='Contact name3')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
