# Generated by Django 4.1.6 on 2023-02-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_live'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Footer name')),
                ('name1', models.CharField(max_length=50, verbose_name='Footer name1')),
                ('name2', models.CharField(max_length=50, verbose_name='Footer name2')),
                ('name3', models.CharField(max_length=50, verbose_name='Footer name3')),
                ('about', models.TextField(verbose_name='Footer about')),
                ('about1', models.TextField(verbose_name='Footer about1')),
                ('about2', models.TextField(verbose_name='Footer about2')),
                ('about3', models.TextField(verbose_name='Footer about3')),
                ('about4', models.TextField(verbose_name='Footer about4')),
                ('about5', models.TextField(verbose_name='Footer about5')),
                ('about6', models.TextField(verbose_name='Footer about6')),
                ('about7', models.TextField(verbose_name='Footer about7')),
                ('about8', models.TextField(verbose_name='Footer about8')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footers',
            },
        ),
    ]
