# Generated by Django 4.1.6 on 2023-02-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_ticketmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ticket name')),
                ('name1', models.CharField(max_length=50, verbose_name='Ticket name1')),
                ('name2', models.CharField(max_length=50, verbose_name='Ticket name2')),
                ('about', models.TextField(verbose_name='Ticket about')),
                ('about1', models.TextField(verbose_name='Ticket about1')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
