# Generated by Django 4.1.6 on 2023-02-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketLive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='TicketLive name')),
            ],
            options={
                'verbose_name': 'TicketLive',
                'verbose_name_plural': 'TicketLives',
            },
        ),
    ]
