# Generated by Django 4.1.6 on 2023-02-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_ticketlive'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketFoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='TicketFoot name')),
                ('name1', models.CharField(max_length=50, verbose_name='TicketFoot name1')),
                ('name2', models.CharField(max_length=50, verbose_name='TicketFoot name2')),
                ('name3', models.CharField(max_length=50, verbose_name='TicketFoot name3')),
                ('about', models.TextField(verbose_name='TicketFoot about')),
                ('about1', models.TextField(verbose_name='TicketFoot about1')),
                ('about2', models.TextField(verbose_name='TicketFoot about2')),
                ('about3', models.TextField(verbose_name='TicketFoot about3')),
                ('about4', models.TextField(verbose_name='TicketFoot about4')),
                ('about5', models.TextField(verbose_name='TicketFoot about5')),
                ('about6', models.TextField(verbose_name='TicketFoot about6')),
                ('about7', models.TextField(verbose_name='TicketFoot about7')),
                ('about8', models.TextField(verbose_name='TicketFoot about8')),
            ],
            options={
                'verbose_name': 'TicketFoot',
                'verbose_name_plural': 'TicketFoots',
            },
        ),
    ]
